# Generated by Django 5.1 on 2025-01-09 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotelbooking',
            old_name='hotelbooking',
            new_name='hotel',
        ),
    ]
