# Generated by Django 5.1 on 2025-01-21 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_hotelbooking_hotelbooking_hotel'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='hotel_rating',
            field=models.IntegerField(default=0),
        ),
    ]
