# Generated by Django 5.1 on 2025-01-21 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_hotel_hotel_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='hotel_rating',
            field=models.FloatField(default=0),
        ),
    ]
