# Generated by Django 5.1 on 2025-01-21 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_hotel_hotel_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='hotel_place',
            field=models.CharField(default='', max_length=200),
        ),
    ]
