# Generated by Django 5.1 on 2025-01-28 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_hotel_hotel_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='login_status',
            field=models.BooleanField(default=False),
        ),
    ]
