# Generated by Django 5.1 on 2025-01-28 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_hotel_login_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='logIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_status', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='login_status',
        ),
    ]
