# Generated by Django 5.1 on 2025-01-28 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_login_remove_hotel_login_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='logIn',
        ),
    ]
